version: '3.8'

networks:
  app-turistica:
    name: app-turistica

services:
  app:
    image: webdevops/php-nginx:8.2
    container_name: app
    restart: on-failure
    working_dir: /app
    ports:
      - "94:80"
    volumes:
      - ./app:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    depends_on:
      - db-turistica
    networks:
      - app-turistica
  
  db-turistica:
    image: mysql:8.0
    container_name: db-turistica
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - ./database/db:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: exito
      MYSQL_DATABASE: dbturistica
    ports:
      - "3312:3306"
    networks:
      - app-turistica